plugins {
    id 'com.android.application'
}

android {
    namespace 'org.pocof7.ctap3b'
    compileSdk 35

    defaultConfig {
        applicationId 'org.pocof7.ctap3b'
        minSdk 31
        targetSdk 35
        versionCode 50101
        versionName '5.1.1-dev'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
