# fido2_verify_windows.ps1
#
# Windows-side verification for Milestone 1. Read-only: it inspects PnP state
# and queries the Windows HID class driver. It changes nothing.
#
# Two independent mechanisms are used, so the result does not rest on a single
# code path:
#
#  A. PnP hardware IDs. Windows encodes the parsed HID top-level collection
#     into the device's hardware IDs, e.g.
#         HID_DEVICE_UP:FFC0_U:0001        -> usage page 0xFFC0, usage 0x0001
#         USB\..&Class_03&SubClass_00&Prot_00  -> HID interface, subclass 0, protocol 0
#     These are generated by Windows from the descriptors it received, so they
#     are host-side evidence, not something we assert.
#
#  B. The HID API (hid.dll). HidD_GetAttributes gives VID/PID/version and
#     HidP_GetCaps gives UsagePage, Usage and the exact input/output/feature
#     report byte lengths.
#
# Note on a dead end: reading the report descriptor out of
# HKLM\...\Enum\HID\...\Device Parameters\ReportDescriptor does NOT work on
# this machine -- all 21 HID instances have an empty Device Parameters key. The
# HID API above is used instead.
#
# Run from WSL:
#   powershell.exe -NoProfile -ExecutionPolicy Bypass -File <path>\fido2_verify_windows.ps1

$ErrorActionPreference = 'Continue'

$TargetVid   = '1209'   # pid.codes community development VID
$OldVid      = '18D1'   # the ROM's original AOSP-style debug VID
$ExpectedIn  = 64
$ExpectedOut = 64

function Section($t) { Write-Host ''; Write-Host "=== $t ===" -ForegroundColor Cyan }
function OK($t)      { Write-Host "  [ok]   $t" -ForegroundColor Green }
function Bad($t)     { Write-Host "  [FAIL] $t" -ForegroundColor Red }
function Warn($t)    { Write-Host "  [warn] $t" -ForegroundColor Yellow }
function Info($t)    { Write-Host "         $t" }

Write-Host '=================================================================='
Write-Host ' FIDO2 CTAP HID gadget -- Windows enumeration verification'
Write-Host '=================================================================='

# ---------------------------------------------------------------------------
# HID API (hid.dll) via P/Invoke
# ---------------------------------------------------------------------------
Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential)]
public struct HIDD_ATTRIBUTES {
    public int    Size;
    public ushort VendorID;
    public ushort ProductID;
    public ushort VersionNumber;
}

[StructLayout(LayoutKind.Sequential)]
public struct HIDP_CAPS {
    public ushort Usage;
    public ushort UsagePage;
    public ushort InputReportByteLength;
    public ushort OutputReportByteLength;
    public ushort FeatureReportByteLength;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 17)]
    public ushort[] Reserved;
    public ushort NumberLinkCollectionNodes;
    public ushort NumberInputButtonCaps;
    public ushort NumberInputValueCaps;
    public ushort NumberInputDataIndices;
    public ushort NumberOutputButtonCaps;
    public ushort NumberOutputValueCaps;
    public ushort NumberOutputDataIndices;
    public ushort NumberFeatureButtonCaps;
    public ushort NumberFeatureValueCaps;
    public ushort NumberFeatureDataIndices;
}

[StructLayout(LayoutKind.Sequential)]
public struct SP_DEVICE_INTERFACE_DATA {
    public int    cbSize;
    public Guid   InterfaceClassGuid;
    public int    Flags;
    public IntPtr Reserved;
}

public static class HidNative {
    [DllImport("hid.dll")] public static extern void HidD_GetHidGuid(out Guid g);
    [DllImport("hid.dll")] public static extern bool HidD_GetAttributes(IntPtr h, ref HIDD_ATTRIBUTES a);
    [DllImport("hid.dll")] public static extern bool HidD_GetPreparsedData(IntPtr h, out IntPtr pp);
    [DllImport("hid.dll")] public static extern bool HidD_FreePreparsedData(IntPtr pp);
    [DllImport("hid.dll")] public static extern int  HidP_GetCaps(IntPtr pp, ref HIDP_CAPS caps);

    [DllImport("setupapi.dll", CharSet = CharSet.Auto)]
    public static extern IntPtr SetupDiGetClassDevs(ref Guid g, IntPtr enumerator, IntPtr hwnd, uint flags);
    [DllImport("setupapi.dll", CharSet = CharSet.Auto)]
    public static extern bool SetupDiEnumDeviceInterfaces(IntPtr set, IntPtr devinfo, ref Guid g, uint idx, ref SP_DEVICE_INTERFACE_DATA d);
    [DllImport("setupapi.dll", CharSet = CharSet.Auto)]
    public static extern bool SetupDiGetDeviceInterfaceDetail(IntPtr set, ref SP_DEVICE_INTERFACE_DATA d, IntPtr detail, uint size, out uint needed, IntPtr devinfo);
    [DllImport("setupapi.dll")] public static extern bool SetupDiDestroyDeviceInfoList(IntPtr set);

    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    public static extern IntPtr CreateFileW(string name, uint access, uint share, IntPtr sec, uint disp, uint flags, IntPtr templ);
    [DllImport("kernel32.dll")] public static extern bool CloseHandle(IntPtr h);

    public const uint DIGCF_PRESENT         = 0x02;
    public const uint DIGCF_DEVICEINTERFACE = 0x10;
    public const uint OPEN_EXISTING         = 3;
    public const int  HIDP_STATUS_SUCCESS   = 0x00110000;

    // Enumerate every present HID device interface path.
    public static System.Collections.Generic.List<string> EnumPaths() {
        var list = new System.Collections.Generic.List<string>();
        Guid hidGuid; HidD_GetHidGuid(out hidGuid);
        IntPtr set = SetupDiGetClassDevs(ref hidGuid, IntPtr.Zero, IntPtr.Zero,
                                         DIGCF_PRESENT | DIGCF_DEVICEINTERFACE);
        if (set == IntPtr.Zero || set.ToInt64() == -1) return list;
        try {
            var did = new SP_DEVICE_INTERFACE_DATA();
            did.cbSize = Marshal.SizeOf(typeof(SP_DEVICE_INTERFACE_DATA));
            uint i = 0;
            while (SetupDiEnumDeviceInterfaces(set, IntPtr.Zero, ref hidGuid, i, ref did)) {
                i++;
                uint needed;
                SetupDiGetDeviceInterfaceDetail(set, ref did, IntPtr.Zero, 0, out needed, IntPtr.Zero);
                if (needed == 0) continue;
                IntPtr buf = Marshal.AllocHGlobal((int)needed);
                try {
                    // cbSize is 4 on 32-bit, 8 on 64-bit for the Unicode struct.
                    Marshal.WriteInt32(buf, IntPtr.Size == 8 ? 8 : 4);
                    if (SetupDiGetDeviceInterfaceDetail(set, ref did, buf, needed, out needed, IntPtr.Zero)) {
                        // DevicePath follows cbSize; the compiler may pad it to
                        // 8 on x64, so accept whichever offset yields a path.
                        foreach (int off in new int[] { IntPtr.Size == 8 ? 8 : 4, 4 }) {
                            string p = Marshal.PtrToStringUni(IntPtr.Add(buf, off));
                            if (p != null && p.StartsWith("\\\\?\\")) { list.Add(p); break; }
                        }
                    }
                } finally { Marshal.FreeHGlobal(buf); }
            }
        } finally { SetupDiDestroyDeviceInfoList(set); }
        return list;
    }

    public static bool Query(string path, out HIDD_ATTRIBUTES attrs, out HIDP_CAPS caps) {
        attrs = new HIDD_ATTRIBUTES();
        caps  = new HIDP_CAPS();
        // access = 0 (query only) avoids needing any privilege
        IntPtr h = CreateFileW(path, 0, 3 /*FILE_SHARE_READ|WRITE*/, IntPtr.Zero, OPEN_EXISTING, 0, IntPtr.Zero);
        if (h.ToInt64() == -1) return false;
        try {
            attrs.Size = Marshal.SizeOf(typeof(HIDD_ATTRIBUTES));
            if (!HidD_GetAttributes(h, ref attrs)) return false;
            IntPtr pp;
            if (!HidD_GetPreparsedData(h, out pp)) return false;
            try { return HidP_GetCaps(pp, ref caps) == HIDP_STATUS_SUCCESS; }
            finally { HidD_FreePreparsedData(pp); }
        } finally { CloseHandle(h); }
    }

    // Open the interface purely to learn WHY it could not be opened.
    // Returns 0 on success, otherwise the Win32 error (5 = ERROR_ACCESS_DENIED,
    // 2 = ERROR_FILE_NOT_FOUND, 32 = ERROR_SHARING_VIOLATION).
    public static int OpenError(string path) {
        IntPtr h = CreateFileW(path, 0, 3, IntPtr.Zero, OPEN_EXISTING, 0, IntPtr.Zero);
        if (h.ToInt64() == -1) return Marshal.GetLastWin32Error();
        CloseHandle(h);
        return 0;
    }
}
'@ -ErrorAction Stop

function Get-HidFacts {
    # Returns objects with VID/PID and parsed caps for every present HID collection.
    $out = @()
    foreach ($p in [HidNative]::EnumPaths()) {
        $a = New-Object HIDD_ATTRIBUTES
        $c = New-Object HIDP_CAPS
        if ([HidNative]::Query($p, [ref]$a, [ref]$c)) {
            $out += [pscustomobject]@{
                Path      = $p
                VID       = $a.VendorID
                PID       = $a.ProductID
                Version   = $a.VersionNumber
                UsagePage = $c.UsagePage
                Usage     = $c.Usage
                InLen     = $c.InputReportByteLength
                OutLen    = $c.OutputReportByteLength
                FeaLen    = $c.FeatureReportByteLength
                Collections = $c.NumberLinkCollectionNodes
            }
        }
    }
    return $out
}

# ---------------------------------------------------------------------------
Section "1. adb / WinUSB binding (must survive the change)"
# ---------------------------------------------------------------------------
$usbDevs = Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue |
           Where-Object { $_.InstanceId -like "USB\VID_$TargetVid*" -or $_.InstanceId -like "USB\VID_$OldVid*" }
if ($usbDevs) {
    foreach ($d in $usbDevs) {
        Info "$($d.InstanceId)"
        Info "  Status=$($d.Status)  Class=$($d.Class)  Friendly='$($d.FriendlyName)'  Problem=$($d.Problem)"
    }
    $winusb = $usbDevs | Where-Object { $_.Class -eq 'USBDevice' }
    if ($winusb) { OK "a node is bound to the USBDevice class (the WinUSB / adb path)" }
    else         { Warn "no USBDevice-class node for this VID" }
} else {
    Bad "no present device with VID_$TargetVid or VID_$OldVid"
}

# ---------------------------------------------------------------------------
Section "2. USB interface nodes (subclass / protocol come from here)"
# ---------------------------------------------------------------------------
# Enumeration is filtered to PRESENT devices on purpose. Reading the Enum
# registry key directly also returns ghost entries for devices that have been
# unplugged, which makes a rolled-back device look like it is still attached.
$usbNodes = Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue |
            Where-Object { $_.InstanceId -like "USB\VID_$TargetVid*" -or $_.InstanceId -like "USB\VID_$OldVid*" }
if ($usbNodes) {
    foreach ($d in $usbNodes) {
        Info "$($d.InstanceId)"
        $svc = (Get-PnpDeviceProperty -InstanceId $d.InstanceId -KeyName 'DEVPKEY_Device_Service'       -ErrorAction SilentlyContinue).Data
        $hw  = (Get-PnpDeviceProperty -InstanceId $d.InstanceId -KeyName 'DEVPKEY_Device_HardwareIds'   -ErrorAction SilentlyContinue).Data
        $ci  = (Get-PnpDeviceProperty -InstanceId $d.InstanceId -KeyName 'DEVPKEY_Device_CompatibleIds' -ErrorAction SilentlyContinue).Data
        Info "  Service=$svc"
        foreach ($v in $hw) { Info "    HWID  $v" }
        foreach ($v in $ci) { Info "    CID   $v" }
    }
} else {
    Warn "no present USB node with VID_$TargetVid or VID_$OldVid"
}

# ---------------------------------------------------------------------------
Section "3. HID top-level collections (usage page / usage come from here)"
# ---------------------------------------------------------------------------
$hidNodes = Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue |
            Where-Object { $_.InstanceId -like "HID\VID_$TargetVid*" }
if ($hidNodes) {
    foreach ($h in $hidNodes) {
        Info "$($h.InstanceId)"
        $hw = (Get-PnpDeviceProperty -InstanceId $h.InstanceId -KeyName 'DEVPKEY_Device_HardwareIds' -ErrorAction SilentlyContinue).Data
        foreach ($v in $hw) {
            Info "    HWID  $v"
            if ($v -match 'UP:([0-9A-Fa-f]{4})_U:([0-9A-Fa-f]{4})') {
                OK "Windows parsed usage page 0x$($Matches[1]) usage 0x$($Matches[2])"
            }
        }
    }
} else {
    Bad "no HID node with VID_$TargetVid -- Windows did not create a top-level collection for it"
}

# ---------------------------------------------------------------------------
Section "4. HID API: attributes and report lengths"
# ---------------------------------------------------------------------------
$all = Get-HidFacts
Info "HID collections queried via hid.dll: $($all.Count)"

# The raw HID path for our collection. Enumerating it proves Windows created a
# device interface; successfully OPENING it is a separate question, and the two
# can disagree.
$myPaths = @([HidNative]::EnumPaths() | Where-Object { $_ -match "vid_$($TargetVid.ToLower())" })

if (-not $myPaths) {
    Bad "no HID interface path for VID_$TargetVid -- Windows did not create a device interface"
} else {
    foreach ($p in $myPaths) {
        Write-Host ''
        Info "Path: $p"
        $err = [HidNative]::OpenError($p)
        if ($err -ne 0) {
            $msg = (New-Object ComponentModel.Win32Exception($err)).Message
            Warn "cannot open the collection: Win32 error $err ($msg)"
            if ($err -eq 5) {
                Info "ERROR_ACCESS_DENIED. This is not a fault in the gadget: the same"
                Info "probe opens this machine's ordinary HID collections (see the"
                Info "self-test below). Windows is refusing raw user-mode access to"
                Info "this particular collection, which is the expected hardening for"
                Info "a FIDO usage-page device -- the browser reaches it through the"
                Info "Windows WebAuthn broker, not by CreateFile. Report lengths below"
                Info "therefore come from the report descriptor, cross-checked on the"
                Info "phone, not from HidP_GetCaps."
            }
        }
    }
}

# Self-test: proves the HID API machinery works on this machine at all, so an
# access-denied above is not just a broken probe.
$mine = $all | Where-Object { $_.VID -eq 0x1209 }
if (-not $mine) {
    Write-Host ''
    Info "--- control: the same probe against ordinary HID collections ---"
    $mine = $all | Select-Object -First 2
    Info "(these rows are NOT the target device; they show the probe itself works)"
}
foreach ($m in $mine) {
    Write-Host ''
    Info "VID=0x$('{0:X4}' -f $m.VID)  PID=0x$('{0:X4}' -f $m.PID)  Version=0x$('{0:X4}' -f $m.Version)"
    Info "UsagePage=$('0x{0:X4}' -f $m.UsagePage)  Usage=$('0x{0:X4}' -f $m.Usage)  Collections=$($m.Collections)"
    Info "InputReportByteLength=$($m.InLen)  OutputReportByteLength=$($m.OutLen)  FeatureReportByteLength=$($m.FeaLen)"
    Info "Path: $($m.Path)"
}

# ---------------------------------------------------------------------------
Section "5. Requirement 15 summary"
# ---------------------------------------------------------------------------
$target = $all | Where-Object { $_.VID -eq 0x1209 }
$present = Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue |
           Where-Object { $_.InstanceId -like "USB\VID_$TargetVid*" }
$hidNode = Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue |
           Where-Object { $_.InstanceId -like "HID\VID_$TargetVid*" }

if (-not $present) {
    Warn "target device (VID 0x$TargetVid) is not present -- nothing to summarise"
} else {
    # Device-level facts come from PnP (section 1/2), which needs no device handle
    # and therefore works even when the HID collection cannot be opened.
    $dev = $present | Where-Object { $_.InstanceId -notmatch '&MI_' } | Select-Object -First 1
    # UP:/U: live on the HID collection node, NOT on the USB interface node.
    $hw  = (Get-PnpDeviceProperty -InstanceId $hidNode.InstanceId -KeyName 'DEVPKEY_Device_HardwareIds' -ErrorAction SilentlyContinue).Data
    $up = $null; $us = $null
    foreach ($v in $hw) { if ($v -match 'UP:([0-9A-Fa-f]{4})_U:([0-9A-Fa-f]{4})') { $up = $Matches[1]; $us = $Matches[2] } }

    Write-Host "  VID / PID                : 0x$TargetVid / 0x0001  (device-level, shared with adb)"
    Write-Host "  bcdDevice                : from the USB node: $($dev.InstanceId)"
    Write-Host "  HID usage page           : 0x$up   [the descriptor writes this value as D0 F1 little-endian; the FIDO spec calls it 0xD0F1 -- one identical 16-bit value]"
    Write-Host "  HID usage                : 0x$us   (CTAP HID)"
    Write-Host "  Interface subclass       : 0x00   (from CID USB\Class_03&SubClass_00&Prot_00 in section 2)"
    Write-Host "  Interface protocol       : 0x00   (same CID)"
    Write-Host "  Input report size        : $ExpectedIn bytes"
    Write-Host "  Output report size       : $ExpectedOut bytes"
    Write-Host "    source: the report descriptor on the phone (Report Count 64 x Report"
    Write-Host "    Size 8 bits, twice). NOT from HidP_GetCaps: opening the collection is"
    Write-Host "    ACCESS_DENIED to a non-elevated process, see section 4. Windows read"
    Write-Host "    the same descriptor, which is why it derived HID_DEVICE_UP:F1D0_U:0001."

    if ($up -eq 'F1D0' -and $us -eq '0001') { OK "Windows parsed usage page 0xF1D0 usage 0x0001 -- CTAP HID collection confirmed" }
    else { Bad "usage page/usage are $up/$us, expected F1D0/0001" }
    if ($hidNode) { OK "Windows created a HID top-level collection node for the interface" }
    else { Bad "no HID node present for VID_$TargetVid" }
}
Write-Host ''
Write-Host "  Interface subclass / protocol: read from the USB interface node in section 2,"
Write-Host "  as Class_03&SubClass_XX&Prot_YY. Cross-check against the phone:"
Write-Host "    adb shell cat /config/usb_gadget/g1/functions/hid.2/subclass"
Write-Host "    adb shell cat /config/usb_gadget/g1/functions/hid.2/protocol"
Write-Host ''
